version: '3.11'


services:
  bot:
    build: .
    working_dir: /apps
    container_name: aiogram_bot
    environment:
      TOKEN: ${TOKEN}
      DATABASE: postgres
      DB_HOST: pg
      DB_USER: postgres
      DB_PORT: 5432
    command: python exem.py
volumes:
  pg_data:




