version: '3.11'


services:
  bot:
    build: .
#    image: spiker007/exem:latest
    working_dir: /apps
    container_name: aiogram_bot
    environment:
      TOKEN: ${TOKEN}
    command: python exem.py





